version: 2
updates:
  - package-ecosystem: maven
    directory: connectivity
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: demos-app
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: error-handling
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: html-dialog
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: quick-start-tutorial
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: rule-engine
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: workflow
    schedule:
      interval: daily
