version: 2
updates:
  - package-ecosystem: maven
    directory: connectivity
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: rule-engine
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: html-dialog
    schedule:
      interval: daily
