/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class TaskInfoCustomFieldsData with the namespace ui.task.TaskInfoCustomFields
 */
package ui.task.TaskInfoCustomFields;

/**
 */
public class TaskInfoCustomFieldsData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 7911852229122209157L;

  /**
   */
  private transient ch.ivyteam.ivy.workflow.ITask task;

  /**
   * Gets the field task.
   * @return the value of the field task; may be null.
   */
  public ch.ivyteam.ivy.workflow.ITask getTask()
  {
    return task;
  }

  /**
   * Sets the field task.
   * @param _task the new value of the field task.
   */
  public void setTask(ch.ivyteam.ivy.workflow.ITask _task)
  {
    task = _task;
  }

}
