/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class ProcessStartListData with the namespace ui.process.ProcessStartList
 */
package ui.process.ProcessStartList;

/**
 */
public class ProcessStartListData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -5555477586031640932L;

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.IProcessStart> starts;

  /**
   * Gets the field starts.
   * @return the value of the field starts; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.IProcessStart> getStarts()
  {
    return starts;
  }

  /**
   * Sets the field starts.
   * @param _starts the new value of the field starts.
   */
  public void setStarts(ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.IProcessStart> _starts)
  {
    starts = _starts;
  }

  /**
   */
  private ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel parentPanel;

  /**
   * Gets the field parentPanel.
   * @return the value of the field parentPanel; may be null.
   */
  public ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel getParentPanel()
  {
    return parentPanel;
  }

  /**
   * Sets the field parentPanel.
   * @param _parentPanel the new value of the field parentPanel.
   */
  public void setParentPanel(ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel _parentPanel)
  {
    parentPanel = _parentPanel;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.IProcessStart selectedStart;

  /**
   * Gets the field selectedStart.
   * @return the value of the field selectedStart; may be null.
   */
  public ch.ivyteam.ivy.workflow.IProcessStart getSelectedStart()
  {
    return selectedStart;
  }

  /**
   * Sets the field selectedStart.
   * @param _selectedStart the new value of the field selectedStart.
   */
  public void setSelectedStart(ch.ivyteam.ivy.workflow.IProcessStart _selectedStart)
  {
    selectedStart = _selectedStart;
  }

}
