/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class TaskExecutionData with the namespace ui.task.TaskExecution
 */
package ui.task.TaskExecution;

/**
 */
public class TaskExecutionData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -5917791203687248784L;

  /**
   */
  private ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel parentPanel;

  /**
   * Gets the field parentPanel.
   * @return the value of the field parentPanel; may be null.
   */
  public ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel getParentPanel()
  {
    return parentPanel;
  }

  /**
   * Sets the field parentPanel.
   * @param _parentPanel the new value of the field parentPanel.
   */
  public void setParentPanel(ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel _parentPanel)
  {
    parentPanel = _parentPanel;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.ITask selectedTask;

  /**
   * Gets the field selectedTask.
   * @return the value of the field selectedTask; may be null.
   */
  public ch.ivyteam.ivy.workflow.ITask getSelectedTask()
  {
    return selectedTask;
  }

  /**
   * Sets the field selectedTask.
   * @param _selectedTask the new value of the field selectedTask.
   */
  public void setSelectedTask(ch.ivyteam.ivy.workflow.ITask _selectedTask)
  {
    selectedTask = _selectedTask;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.WorkflowSystemEventParameter wfEventParam;

  /**
   * Gets the field wfEventParam.
   * @return the value of the field wfEventParam; may be null.
   */
  public ch.ivyteam.ivy.workflow.WorkflowSystemEventParameter getWfEventParam()
  {
    return wfEventParam;
  }

  /**
   * Sets the field wfEventParam.
   * @param _wfEventParam the new value of the field wfEventParam.
   */
  public void setWfEventParam(ch.ivyteam.ivy.workflow.WorkflowSystemEventParameter _wfEventParam)
  {
    wfEventParam = _wfEventParam;
  }

}
