/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class TaskInfoData with the namespace ui.task.TaskInfo
 */
package ui.task.TaskInfo;

/**
 */
public class TaskInfoData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -7765810834106653522L;

  /**
   */
  private java.lang.String info;

  /**
   * Gets the field info.
   * @return the value of the field info; may be null.
   */
  public java.lang.String getInfo()
  {
    return info;
  }

  /**
   * Sets the field info.
   * @param _info the new value of the field info.
   */
  public void setInfo(java.lang.String _info)
  {
    info = _info;
  }

}
