/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class loginData with the namespace ui.basic.login
 */
package ui.basic.login;

/**
 */
public class loginData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -3623193905065159397L;

  /**
   */
  private java.lang.String name;

  /**
   * Gets the field name.
   * @return the value of the field name; may be null.
   */
  public java.lang.String getName()
  {
    return name;
  }

  /**
   * Sets the field name.
   * @param _name the new value of the field name.
   */
  public void setName(java.lang.String _name)
  {
    name = _name;
  }

  /**
   */
  private java.lang.String pw;

  /**
   * Gets the field pw.
   * @return the value of the field pw; may be null.
   */
  public java.lang.String getPw()
  {
    return pw;
  }

  /**
   * Sets the field pw.
   * @param _pw the new value of the field pw.
   */
  public void setPw(java.lang.String _pw)
  {
    pw = _pw;
  }

  /**
   */
  private java.lang.String msg;

  /**
   * Gets the field msg.
   * @return the value of the field msg; may be null.
   */
  public java.lang.String getMsg()
  {
    return msg;
  }

  /**
   * Sets the field msg.
   * @param _msg the new value of the field msg.
   */
  public void setMsg(java.lang.String _msg)
  {
    msg = _msg;
  }

}
