/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class mainData with the namespace ui.basic.main
 */
package ui.basic.main;

/**
 */
public class mainData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 0L;

}
