package ch.ivyteam.demo.jpa.demos.ivy;

public enum WorkflowId {
	PROJECT,
	PROJECT_STATUS_REPORT_FINALIZATION_REMINDER,
	QA_STATUS_REPORT_FINALIZATION_REMINDER,
	RISK_CATALOG_REPORT_FINALIZATION_REMINDER,
	;

}
