/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class ArchivePageDetail with the namespace htmlwfui
 */
package htmlwfui;

/**
 */
public class ArchivePageDetail extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -7917242730899172683L;

  /**
   */
  private java.lang.String name;

  /**
   * Gets the field name.
   * @return the value of the field name; may be null.
   */
  public java.lang.String getName()
  {
    return name;
  }

  /**
   * Sets the field name.
   * @param _name the new value of the field name.
   */
  public void setName(java.lang.String _name)
  {
    name = _name;
  }

  /**
   */
  private java.lang.String ref;

  /**
   * Gets the field ref.
   * @return the value of the field ref; may be null.
   */
  public java.lang.String getRef()
  {
    return ref;
  }

  /**
   * Sets the field ref.
   * @param _ref the new value of the field ref.
   */
  public void setRef(java.lang.String _ref)
  {
    ref = _ref;
  }

  /**
   */
  private java.lang.Number id;

  /**
   * Gets the field id.
   * @return the value of the field id; may be null.
   */
  public java.lang.Number getId()
  {
    return id;
  }

  /**
   * Sets the field id.
   * @param _id the new value of the field id.
   */
  public void setId(java.lang.Number _id)
  {
    id = _id;
  }

}
