/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class Data with the namespace htmlwfui
 */
package htmlwfui;

/**
 */
public class Data extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 8677411816900900078L;

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ITask> tasks;

  /**
   * Gets the field tasks.
   * @return the value of the field tasks; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ITask> getTasks()
  {
    return tasks;
  }

  /**
   * Sets the field tasks.
   * @param _tasks the new value of the field tasks.
   */
  public void setTasks(ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ITask> _tasks)
  {
    tasks = _tasks;
  }

  /**
   */
  private java.lang.String username;

  /**
   * Gets the field username.
   * @return the value of the field username; may be null.
   */
  public java.lang.String getUsername()
  {
    return username;
  }

  /**
   * Sets the field username.
   * @param _username the new value of the field username.
   */
  public void setUsername(java.lang.String _username)
  {
    username = _username;
  }

  /**
   */
  private java.lang.String password;

  /**
   * Gets the field password.
   * @return the value of the field password; may be null.
   */
  public java.lang.String getPassword()
  {
    return password;
  }

  /**
   * Sets the field password.
   * @param _password the new value of the field password.
   */
  public void setPassword(java.lang.String _password)
  {
    password = _password;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.ITask tmpTask;

  /**
   * Gets the field tmpTask.
   * @return the value of the field tmpTask; may be null.
   */
  public ch.ivyteam.ivy.workflow.ITask getTmpTask()
  {
    return tmpTask;
  }

  /**
   * Sets the field tmpTask.
   * @param _tmpTask the new value of the field tmpTask.
   */
  public void setTmpTask(ch.ivyteam.ivy.workflow.ITask _tmpTask)
  {
    tmpTask = _tmpTask;
  }

  /**
   */
  private java.lang.Number tmpTaskId;

  /**
   * Gets the field tmpTaskId.
   * @return the value of the field tmpTaskId; may be null.
   */
  public java.lang.Number getTmpTaskId()
  {
    return tmpTaskId;
  }

  /**
   * Sets the field tmpTaskId.
   * @param _tmpTaskId the new value of the field tmpTaskId.
   */
  public void setTmpTaskId(java.lang.Number _tmpTaskId)
  {
    tmpTaskId = _tmpTaskId;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.IWorkflowSession wfSession;

  /**
   * Gets the field wfSession.
   * @return the value of the field wfSession; may be null.
   */
  public ch.ivyteam.ivy.workflow.IWorkflowSession getWfSession()
  {
    return wfSession;
  }

  /**
   * Sets the field wfSession.
   * @param _wfSession the new value of the field wfSession.
   */
  public void setWfSession(ch.ivyteam.ivy.workflow.IWorkflowSession _wfSession)
  {
    wfSession = _wfSession;
  }

  /**
   */
  private java.lang.String delegateType;

  /**
   * Gets the field delegateType.
   * @return the value of the field delegateType; may be null.
   */
  public java.lang.String getDelegateType()
  {
    return delegateType;
  }

  /**
   * Sets the field delegateType.
   * @param _delegateType the new value of the field delegateType.
   */
  public void setDelegateType(java.lang.String _delegateType)
  {
    delegateType = _delegateType;
  }

  /**
   */
  private java.lang.String delegateUser;

  /**
   * Gets the field delegateUser.
   * @return the value of the field delegateUser; may be null.
   */
  public java.lang.String getDelegateUser()
  {
    return delegateUser;
  }

  /**
   * Sets the field delegateUser.
   * @param _delegateUser the new value of the field delegateUser.
   */
  public void setDelegateUser(java.lang.String _delegateUser)
  {
    delegateUser = _delegateUser;
  }

  /**
   */
  private java.lang.String delegateRole;

  /**
   * Gets the field delegateRole.
   * @return the value of the field delegateRole; may be null.
   */
  public java.lang.String getDelegateRole()
  {
    return delegateRole;
  }

  /**
   * Sets the field delegateRole.
   * @param _delegateRole the new value of the field delegateRole.
   */
  public void setDelegateRole(java.lang.String _delegateRole)
  {
    delegateRole = _delegateRole;
  }

  /**
   */
  private ch.ivyteam.ivy.request.IProcessModelVersionRequest request;

  /**
   * Gets the field request.
   * @return the value of the field request; may be null.
   */
  public ch.ivyteam.ivy.request.IProcessModelVersionRequest getRequest()
  {
    return request;
  }

  /**
   * Sets the field request.
   * @param _request the new value of the field request.
   */
  public void setRequest(ch.ivyteam.ivy.request.IProcessModelVersionRequest _request)
  {
    request = _request;
  }

  /**
   */
  private java.lang.String noteFor;

  /**
   * Gets the field noteFor.
   * @return the value of the field noteFor; may be null.
   */
  public java.lang.String getNoteFor()
  {
    return noteFor;
  }

  /**
   * Sets the field noteFor.
   * @param _noteFor the new value of the field noteFor.
   */
  public void setNoteFor(java.lang.String _noteFor)
  {
    noteFor = _noteFor;
  }

  /**
   */
  private java.lang.String note;

  /**
   * Gets the field note.
   * @return the value of the field note; may be null.
   */
  public java.lang.String getNote()
  {
    return note;
  }

  /**
   * Sets the field note.
   * @param _note the new value of the field note.
   */
  public void setNote(java.lang.String _note)
  {
    note = _note;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<Object> ivy3Tasks;

  /**
   * Gets the field ivy3Tasks.
   * @return the value of the field ivy3Tasks; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<Object> getIvy3Tasks()
  {
    return ivy3Tasks;
  }

  /**
   * Sets the field ivy3Tasks.
   * @param _ivy3Tasks the new value of the field ivy3Tasks.
   */
  public void setIvy3Tasks(ch.ivyteam.ivy.scripting.objects.List<Object> _ivy3Tasks)
  {
    ivy3Tasks = _ivy3Tasks;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.IProcessStart> starts;

  /**
   * Gets the field starts.
   * @return the value of the field starts; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.IProcessStart> getStarts()
  {
    return starts;
  }

  /**
   * Sets the field starts.
   * @param _starts the new value of the field starts.
   */
  public void setStarts(ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.IProcessStart> _starts)
  {
    starts = _starts;
  }

  /**
   */
  private java.lang.String appname;

  /**
   * Gets the field appname.
   * @return the value of the field appname; may be null.
   */
  public java.lang.String getAppname()
  {
    return appname;
  }

  /**
   * Sets the field appname.
   * @param _appname the new value of the field appname.
   */
  public void setAppname(java.lang.String _appname)
  {
    appname = _appname;
  }

  /**
   */
  private htmlwfui.TaskDetail x;

  /**
   * Gets the field x.
   * @return the value of the field x; may be null.
   */
  public htmlwfui.TaskDetail getX()
  {
    return x;
  }

  /**
   * Sets the field x.
   * @param _x the new value of the field x.
   */
  public void setX(htmlwfui.TaskDetail _x)
  {
    x = _x;
  }

  /**
   */
  private htmlwfui.TaskDetail tmpTaskDetail;

  /**
   * Gets the field tmpTaskDetail.
   * @return the value of the field tmpTaskDetail; may be null.
   */
  public htmlwfui.TaskDetail getTmpTaskDetail()
  {
    return tmpTaskDetail;
  }

  /**
   * Sets the field tmpTaskDetail.
   * @param _tmpTaskDetail the new value of the field tmpTaskDetail.
   */
  public void setTmpTaskDetail(htmlwfui.TaskDetail _tmpTaskDetail)
  {
    tmpTaskDetail = _tmpTaskDetail;
  }

  /**
   */
  private java.lang.String tmpTask3Id;

  /**
   * Gets the field tmpTask3Id.
   * @return the value of the field tmpTask3Id; may be null.
   */
  public java.lang.String getTmpTask3Id()
  {
    return tmpTask3Id;
  }

  /**
   * Sets the field tmpTask3Id.
   * @param _tmpTask3Id the new value of the field tmpTask3Id.
   */
  public void setTmpTask3Id(java.lang.String _tmpTask3Id)
  {
    tmpTask3Id = _tmpTask3Id;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ICase> cases;

  /**
   * Gets the field cases.
   * @return the value of the field cases; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ICase> getCases()
  {
    return cases;
  }

  /**
   * Sets the field cases.
   * @param _cases the new value of the field cases.
   */
  public void setCases(ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ICase> _cases)
  {
    cases = _cases;
  }

  /**
   */
  private htmlwfui.Temporary temp;

  /**
   * Gets the field temp.
   * @return the value of the field temp; may be null.
   */
  public htmlwfui.Temporary getTemp()
  {
    return temp;
  }

  /**
   * Sets the field temp.
   * @param _temp the new value of the field temp.
   */
  public void setTemp(htmlwfui.Temporary _temp)
  {
    temp = _temp;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.ICase tempCase;

  /**
   * Gets the field tempCase.
   * @return the value of the field tempCase; may be null.
   */
  public ch.ivyteam.ivy.workflow.ICase getTempCase()
  {
    return tempCase;
  }

  /**
   * Sets the field tempCase.
   * @param _tempCase the new value of the field tempCase.
   */
  public void setTempCase(ch.ivyteam.ivy.workflow.ICase _tempCase)
  {
    tempCase = _tempCase;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<htmlwfui.ArchivePageDetail> pageArchives;

  /**
   * Gets the field pageArchives.
   * @return the value of the field pageArchives; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<htmlwfui.ArchivePageDetail> getPageArchives()
  {
    return pageArchives;
  }

  /**
   * Sets the field pageArchives.
   * @param _pageArchives the new value of the field pageArchives.
   */
  public void setPageArchives(ch.ivyteam.ivy.scripting.objects.List<htmlwfui.ArchivePageDetail> _pageArchives)
  {
    pageArchives = _pageArchives;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<htmlwfui.TaskDetail> taskList;

  /**
   * Gets the field taskList.
   * @return the value of the field taskList; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<htmlwfui.TaskDetail> getTaskList()
  {
    return taskList;
  }

  /**
   * Sets the field taskList.
   * @param _taskList the new value of the field taskList.
   */
  public void setTaskList(ch.ivyteam.ivy.scripting.objects.List<htmlwfui.TaskDetail> _taskList)
  {
    taskList = _taskList;
  }

}
