/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class TaskDetail with the namespace htmlwfui
 */
package htmlwfui;

/**
 */
public class TaskDetail extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -364866319057427928L;

  /**
   */
  private java.lang.String activator;

  /**
   * Gets the field activator.
   * @return the value of the field activator; may be null.
   */
  public java.lang.String getActivator()
  {
    return activator;
  }

  /**
   * Sets the field activator.
   * @param _activator the new value of the field activator.
   */
  public void setActivator(java.lang.String _activator)
  {
    activator = _activator;
  }

  /**
   */
  private java.lang.String activatorIsUser;

  /**
   * Gets the field activatorIsUser.
   * @return the value of the field activatorIsUser; may be null.
   */
  public java.lang.String getActivatorIsUser()
  {
    return activatorIsUser;
  }

  /**
   * Sets the field activatorIsUser.
   * @param _activatorIsUser the new value of the field activatorIsUser.
   */
  public void setActivatorIsUser(java.lang.String _activatorIsUser)
  {
    activatorIsUser = _activatorIsUser;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.DateTime delay;

  /**
   * Gets the field delay.
   * @return the value of the field delay; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.DateTime getDelay()
  {
    return delay;
  }

  /**
   * Sets the field delay.
   * @param _delay the new value of the field delay.
   */
  public void setDelay(ch.ivyteam.ivy.scripting.objects.DateTime _delay)
  {
    delay = _delay;
  }

  /**
   */
  private java.lang.String delayStr;

  /**
   * Gets the field delayStr.
   * @return the value of the field delayStr; may be null.
   */
  public java.lang.String getDelayStr()
  {
    return delayStr;
  }

  /**
   * Sets the field delayStr.
   * @param _delayStr the new value of the field delayStr.
   */
  public void setDelayStr(java.lang.String _delayStr)
  {
    delayStr = _delayStr;
  }

  /**
   */
  private java.lang.String desc;

  /**
   * Gets the field desc.
   * @return the value of the field desc; may be null.
   */
  public java.lang.String getDesc()
  {
    return desc;
  }

  /**
   * Sets the field desc.
   * @param _desc the new value of the field desc.
   */
  public void setDesc(java.lang.String _desc)
  {
    desc = _desc;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.DateTime exp;

  /**
   * Gets the field exp.
   * @return the value of the field exp; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.DateTime getExp()
  {
    return exp;
  }

  /**
   * Sets the field exp.
   * @param _exp the new value of the field exp.
   */
  public void setExp(ch.ivyteam.ivy.scripting.objects.DateTime _exp)
  {
    exp = _exp;
  }

  /**
   */
  private java.lang.String expStr;

  /**
   * Gets the field expStr.
   * @return the value of the field expStr; may be null.
   */
  public java.lang.String getExpStr()
  {
    return expStr;
  }

  /**
   * Sets the field expStr.
   * @param _expStr the new value of the field expStr.
   */
  public void setExpStr(java.lang.String _expStr)
  {
    expStr = _expStr;
  }

  /**
   */
  private java.lang.String id;

  /**
   * Gets the field id.
   * @return the value of the field id; may be null.
   */
  public java.lang.String getId()
  {
    return id;
  }

  /**
   * Sets the field id.
   * @param _id the new value of the field id.
   */
  public void setId(java.lang.String _id)
  {
    id = _id;
  }

  /**
   */
  private java.lang.String name;

  /**
   * Gets the field name.
   * @return the value of the field name; may be null.
   */
  public java.lang.String getName()
  {
    return name;
  }

  /**
   * Sets the field name.
   * @param _name the new value of the field name.
   */
  public void setName(java.lang.String _name)
  {
    name = _name;
  }

  /**
   */
  private java.lang.String prio;

  /**
   * Gets the field prio.
   * @return the value of the field prio; may be null.
   */
  public java.lang.String getPrio()
  {
    return prio;
  }

  /**
   * Sets the field prio.
   * @param _prio the new value of the field prio.
   */
  public void setPrio(java.lang.String _prio)
  {
    prio = _prio;
  }

  /**
   */
  private java.lang.String start;

  /**
   * Gets the field start.
   * @return the value of the field start; may be null.
   */
  public java.lang.String getStart()
  {
    return start;
  }

  /**
   * Sets the field start.
   * @param _start the new value of the field start.
   */
  public void setStart(java.lang.String _start)
  {
    start = _start;
  }

  /**
   */
  private java.lang.String state;

  /**
   * Gets the field state.
   * @return the value of the field state; may be null.
   */
  public java.lang.String getState()
  {
    return state;
  }

  /**
   * Sets the field state.
   * @param _state the new value of the field state.
   */
  public void setState(java.lang.String _state)
  {
    state = _state;
  }

  /**
   */
  private java.lang.String url;

  /**
   * Gets the field url.
   * @return the value of the field url; may be null.
   */
  public java.lang.String getUrl()
  {
    return url;
  }

  /**
   * Sets the field url.
   * @param _url the new value of the field url.
   */
  public void setUrl(java.lang.String _url)
  {
    url = _url;
  }

}
