/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class Temporary with the namespace htmlwfui
 */
package htmlwfui;

/**
 */
public class Temporary extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 1828570399275310009L;

  /**
   */
  private java.lang.String caption;

  /**
   * Gets the field caption.
   * @return the value of the field caption; may be null.
   */
  public java.lang.String getCaption()
  {
    return caption;
  }

  /**
   * Sets the field caption.
   * @param _caption the new value of the field caption.
   */
  public void setCaption(java.lang.String _caption)
  {
    caption = _caption;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<java.lang.String> categories;

  /**
   * Gets the field categories.
   * @return the value of the field categories; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<java.lang.String> getCategories()
  {
    return categories;
  }

  /**
   * Sets the field categories.
   * @param _categories the new value of the field categories.
   */
  public void setCategories(ch.ivyteam.ivy.scripting.objects.List<java.lang.String> _categories)
  {
    categories = _categories;
  }

  /**
   */
  private java.lang.String catFilter;

  /**
   * Gets the field catFilter.
   * @return the value of the field catFilter; may be null.
   */
  public java.lang.String getCatFilter()
  {
    return catFilter;
  }

  /**
   * Sets the field catFilter.
   * @param _catFilter the new value of the field catFilter.
   */
  public void setCatFilter(java.lang.String _catFilter)
  {
    catFilter = _catFilter;
  }

  /**
   */
  private java.lang.String msg;

  /**
   * Gets the field msg.
   * @return the value of the field msg; may be null.
   */
  public java.lang.String getMsg()
  {
    return msg;
  }

  /**
   * Sets the field msg.
   * @param _msg the new value of the field msg.
   */
  public void setMsg(java.lang.String _msg)
  {
    msg = _msg;
  }

  /**
   */
  private java.lang.Number n;

  /**
   * Gets the field n.
   * @return the value of the field n; may be null.
   */
  public java.lang.Number getN()
  {
    return n;
  }

  /**
   * Sets the field n.
   * @param _n the new value of the field n.
   */
  public void setN(java.lang.Number _n)
  {
    n = _n;
  }

  /**
   */
  private java.lang.Boolean ok;

  /**
   * Gets the field ok.
   * @return the value of the field ok; may be null.
   */
  public java.lang.Boolean getOk()
  {
    return ok;
  }

  /**
   * Sets the field ok.
   * @param _ok the new value of the field ok.
   */
  public void setOk(java.lang.Boolean _ok)
  {
    ok = _ok;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<Object> opts;

  /**
   * Gets the field opts.
   * @return the value of the field opts; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<Object> getOpts()
  {
    return opts;
  }

  /**
   * Sets the field opts.
   * @param _opts the new value of the field opts.
   */
  public void setOpts(ch.ivyteam.ivy.scripting.objects.List<Object> _opts)
  {
    opts = _opts;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.Recordset processes;

  /**
   * Gets the field processes.
   * @return the value of the field processes; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.Recordset getProcesses()
  {
    return processes;
  }

  /**
   * Sets the field processes.
   * @param _processes the new value of the field processes.
   */
  public void setProcesses(ch.ivyteam.ivy.scripting.objects.Recordset _processes)
  {
    processes = _processes;
  }

  /**
   */
  private java.lang.String procFilter;

  /**
   * Gets the field procFilter.
   * @return the value of the field procFilter; may be null.
   */
  public java.lang.String getProcFilter()
  {
    return procFilter;
  }

  /**
   * Sets the field procFilter.
   * @param _procFilter the new value of the field procFilter.
   */
  public void setProcFilter(java.lang.String _procFilter)
  {
    procFilter = _procFilter;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<java.lang.String> states;

  /**
   * Gets the field states.
   * @return the value of the field states; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<java.lang.String> getStates()
  {
    return states;
  }

  /**
   * Sets the field states.
   * @param _states the new value of the field states.
   */
  public void setStates(ch.ivyteam.ivy.scripting.objects.List<java.lang.String> _states)
  {
    states = _states;
  }

  /**
   */
  private java.lang.String statFilter;

  /**
   * Gets the field statFilter.
   * @return the value of the field statFilter; may be null.
   */
  public java.lang.String getStatFilter()
  {
    return statFilter;
  }

  /**
   * Sets the field statFilter.
   * @param _statFilter the new value of the field statFilter.
   */
  public void setStatFilter(java.lang.String _statFilter)
  {
    statFilter = _statFilter;
  }

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.Recordset processesCombo;

  /**
   * Gets the field processesCombo.
   * @return the value of the field processesCombo; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.Recordset getProcessesCombo()
  {
    return processesCombo;
  }

  /**
   * Sets the field processesCombo.
   * @param _processesCombo the new value of the field processesCombo.
   */
  public void setProcessesCombo(ch.ivyteam.ivy.scripting.objects.Recordset _processesCombo)
  {
    processesCombo = _processesCombo;
  }

}
