WebServiceClients:
  policyGreeter:
    Id: 162AF1AE2B935160
    WsdlUrl: http://test-webservices.ivyteam.io:8080/country-service/webservices/greet-policy-wss?wsdl
    WsCallLibrary: CXF
    ServiceClass: ch.ivyteam.testservice.policy.greeter.client.SecureGreetPolicyServiceService
    Features:
    - ch.ivyteam.ivy.webservice.exec.cxf.feature.policy.IgnorePolicyFeature
    Properties:
      policy.disabled: http://schemas.xmlsoap.org/ws/2005/07/securitypolicy:SupportingTokens
    Endpoints:
      SecureGreetPolicyServicePort:
      - http://test-webservices.ivyteam.io:8080/country-service/webservices/greet-policy-wss
