/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class tasklistData with the namespace ui.task.tasklist
 */
package ui.task.tasklist;

/**
 */
public class tasklistData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -3998809182218975200L;

  /**
   */
  private ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ITask> tasks;

  /**
   * Gets the field tasks.
   * @return the value of the field tasks; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ITask> getTasks()
  {
    return tasks;
  }

  /**
   * Sets the field tasks.
   * @param _tasks the new value of the field tasks.
   */
  public void setTasks(ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.workflow.ITask> _tasks)
  {
    tasks = _tasks;
  }

  /**
   */
  private ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel parentPanel;

  /**
   * Gets the field parentPanel.
   * @return the value of the field parentPanel; may be null.
   */
  public ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel getParentPanel()
  {
    return parentPanel;
  }

  /**
   * Sets the field parentPanel.
   * @param _parentPanel the new value of the field parentPanel.
   */
  public void setParentPanel(ch.ivyteam.ivy.richdialog.rdpanels.RichDialogBorderPanel _parentPanel)
  {
    parentPanel = _parentPanel;
  }

  /**
   */
  private ch.ivyteam.ivy.workflow.ITask selectedTask;

  /**
   * Gets the field selectedTask.
   * @return the value of the field selectedTask; may be null.
   */
  public ch.ivyteam.ivy.workflow.ITask getSelectedTask()
  {
    return selectedTask;
  }

  /**
   * Sets the field selectedTask.
   * @param _selectedTask the new value of the field selectedTask.
   */
  public void setSelectedTask(ch.ivyteam.ivy.workflow.ITask _selectedTask)
  {
    selectedTask = _selectedTask;
  }

}
