/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class CaseInfoCustomFieldsData with the namespace ui.cases.CaseInfoCustomFields
 */
package ui.cases.CaseInfoCustomFields;

/**
 */
public class CaseInfoCustomFieldsData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 7909677030142987446L;

  /**
   */
  private transient ch.ivyteam.ivy.workflow.ICase fCase;

  /**
   * Gets the field fCase.
   * @return the value of the field fCase; may be null.
   */
  public ch.ivyteam.ivy.workflow.ICase getFCase()
  {
    return fCase;
  }

  /**
   * Sets the field fCase.
   * @param _fCase the new value of the field fCase.
   */
  public void setFCase(ch.ivyteam.ivy.workflow.ICase _fCase)
  {
    fCase = _fCase;
  }

}
