/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class Data with the namespace basicwfui
 */
package basicwfui;

/**
 */
public class Data extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = 0L;

}
