WebServiceClients:
  personService:
    Id: 16150E44A158D09C
    WsdlUrl: http://127.0.0.1:8081/designer/ws/connectivity-demos/16150E1D07E8CA18?WSDL
    WsCallLibrary: CXF
    ServiceClass: com.axonivy.connectivity.soap.service.client.PersonServiceService
    Features:
    - ch.ivyteam.ivy.webservice.exec.cxf.feature.HttpBasicAuthenticationFeature
    Properties:
      username: theBoss
      password: ${decrypt:\u007B\u0012\u0012\u0075\u002F\u0017\u00D1\u0083\u00C4\u009C\u0094\u00B0\u009A\u00B2\u00ED\u006B\u00AE\u000D\u005A\u0007\u0032\u009C\u0070\u00D6\u006F\u0027\u0008\u0080\u0085\u00CA\u005F\u00B5\u0094\u006C\u0091\u002D\u001A\u00F9\u0082\u0013\u004E\u00C4\u00C0\u0099\u00DA\u003B\u00C4\u0074}
    Endpoints:
      PersonServicePort:
      - '{ivy.engine.baseurl}/ws/connectivity-demos/16150E1D07E8CA18'
  technicalBackend:
    Id: 162B962523BAAB85
    WsdlUrl: http://localhost:8081/designer/ws/connectivity-demos/162B95BB70C3178E?WSDL
    WsCallLibrary: CXF
    ServiceClass: com.axonivy.connectivity.client.TechnicalBackendServiceService
    Endpoints:
      TechnicalBackendServicePort:
      - '{ivy.engine.baseurl}/ws/connectivity-demos/162B95BB70C3178E'
  smartbearTests:
    Id: 162B97C859B22CA3
    WsdlUrl: http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx?WSDL
    WsCallLibrary: CXF
    ServiceClass: com.smartbear.sample.test.client.SampleWebService
    Endpoints:
      SampleWebServiceSoap:
      - http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx
      SampleWebServiceSoap12:
      - http://secure.smartbearsoftware.com/samples/testcomplete12/webservices/Service.asmx
  interceptedService:
    Id: 16D2A643A3A25C52
    WsdlUrl: http://localhost:8081/designer/ws/connectivity-demos/16D29AE50A7A6E34?WSDL
    WsCallLibrary: CXF
    ServiceClass: com.axonivy.connectivity.soap.interceptor.client.ServiceWithExceptionService
    Endpoints:
      ServiceWithExceptionPort:
      - '{ivy.engine.baseurl}/ws/connectivity-demos/16D29AE50A7A6E34'
