/*
 * This file is automatically generated!
 * Do not edit this file!
 *
 * This is the java file of the ivy data class TaskNotesData with the namespace ui.task.TaskNotes
 */
package ui.task.TaskNotes;

/**
 */
public class TaskNotesData extends ch.ivyteam.ivy.scripting.objects.CompositeObject
{
  /** SerialVersionUID */
  private static final long serialVersionUID = -6223288892458561607L;

  /**
   */
  private transient ch.ivyteam.ivy.workflow.ITask task;

  /**
   * Gets the field task.
   * @return the value of the field task; may be null.
   */
  public ch.ivyteam.ivy.workflow.ITask getTask()
  {
    return task;
  }

  /**
   * Sets the field task.
   * @param _task the new value of the field task.
   */
  public void setTask(ch.ivyteam.ivy.workflow.ITask _task)
  {
    task = _task;
  }

  /**
   * If the data should be loaded at RD start
   */
  private transient java.lang.Boolean loadDataAtStart;

  /**
   * Gets the field loadDataAtStart.
   * @return the value of the field loadDataAtStart; may be null.
   */
  public java.lang.Boolean getLoadDataAtStart()
  {
    return loadDataAtStart;
  }

  /**
   * Sets the field loadDataAtStart.
   * @param _loadDataAtStart the new value of the field loadDataAtStart.
   */
  public void setLoadDataAtStart(java.lang.Boolean _loadDataAtStart)
  {
    loadDataAtStart = _loadDataAtStart;
  }

  /**
   */
  private transient ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.scripting.objects.Tree> taskNotes;

  /**
   * Gets the field taskNotes.
   * @return the value of the field taskNotes; may be null.
   */
  public ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.scripting.objects.Tree> getTaskNotes()
  {
    return taskNotes;
  }

  /**
   * Sets the field taskNotes.
   * @param _taskNotes the new value of the field taskNotes.
   */
  public void setTaskNotes(ch.ivyteam.ivy.scripting.objects.List<ch.ivyteam.ivy.scripting.objects.Tree> _taskNotes)
  {
    taskNotes = _taskNotes;
  }

  /**
   */
  private transient ch.ivyteam.ivy.workflow.INote currentNote;

  /**
   * Gets the field currentNote.
   * @return the value of the field currentNote; may be null.
   */
  public ch.ivyteam.ivy.workflow.INote getCurrentNote()
  {
    return currentNote;
  }

  /**
   * Sets the field currentNote.
   * @param _currentNote the new value of the field currentNote.
   */
  public void setCurrentNote(ch.ivyteam.ivy.workflow.INote _currentNote)
  {
    currentNote = _currentNote;
  }

}
