package rules.rule.engine.demo.drl
import rule.engine.demo.Member;
import rule.engine.demo.enums.MemberType

dialect "mvel"

rule "No discount"
	when
		$member: Member(memberType == null || (purchaseAmount < 500 && memberType == MemberType.Silver))
	then
		$member.discount = 0
end

rule "Low discount"
	when
		$member: Member(purchaseAmount < 500 && memberType == MemberType.Gold)
	then
		$member.discount = 2
end

rule "Low-medium discount"
	when
		$member: Member(purchaseAmount >= 500 && purchaseAmount < 2000 && memberType == MemberType.Silver)
	then
		$member.discount = 3
end

rule "High-medium discount"
	when
		$member: Member(purchaseAmount >= 2000 && memberType == MemberType.Silver)
	then
		$member.discount = 5
end

rule "High discount"
	when
		$member: Member(purchaseAmount >= 500 && purchaseAmount < 2000 && memberType == MemberType.Gold)
	then
		$member.discount = 8
end

rule "Advanced discount"
	when
		$member: Member(purchaseAmount >= 2000 && memberType == MemberType.Gold)
	then
		$member.discount = 10
end