name: CI-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v4
    with:
      mvnArgs: -Dmaven.test.failure.ignore=true
